server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  issuer: issuer
  secret-key: secret-key
  expires_in: 60 # 60분
  refresh-expires_in: 10080 # 7일 (7*24*60)

oauth:
  kakao:
    authorization_code_request_uri: https://kauth.kakao.com/oauth/authorize
    token_request_uri: https://kauth.kakao.com/oauth/token
    token_info_request_uri: https://kapi.kakao.com/v1/user/access_token_info
    client_id: client_id
    redirect_uri: redirect_uri
    client_secret: client_secret

book:
  naver:
    client-id: client_id
    client-secret: client-secret
    search-request-uri: https://openapi.naver.com/v1/search/book.json
